replicaCount: 2
image:
  repository: ghcr.io/arman/vitrin-site
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
