changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - feat
    - title: 🐛 Fixes
      labels:
        - fix
        - bug
    - title: 🧹 Maintenance
      labels:
        - chore
        - refactor
        - deps
    - title: ⚙️ CI/CD
      labels:
        - ci
