apiVersion: v1
kind: Service
metadata:
  name: backend-stable
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 4000
