apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
spec:
  replicas: 3
  strategy:
    canary:
      canaryService: backend-canary
      stableService: backend-stable
      trafficRouting:
        nginx: {}
      steps:
      - setWeight: 20
      - pause: { duration: 60 }
      - setWeight: 50
      - pause: { duration: 120 }
      - setWeight: 100
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-org/backend:latest
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet: { path: /health, port: 4000 }
          initialDelaySeconds: 5
          periodSeconds: 10
