version: "3.8"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: {}

# added by phase2
x-default-healthcheck: &default-healthcheck
  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:${PORT:-3000}/health || exit 1"]
    interval: 30s
    timeout: 3s
    retries: 3
