receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlp:
    endpoint: http://otel-collector:4317
    tls:
      insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]