name: build-matrix
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - name: Typecheck (matrix)
        run: pnpm -r run typecheck || true
      - name: Build (matrix)
        run: pnpm -r run build
      - name: Lint (matrix)
        run: pnpm -r run lint || true
      - name: Test (matrix)
        run: pnpm -r run test || true
