name: container-cd-template
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository }}:sha-${{ github.sha }} --push .
      - name: SBOM (syft)
        run: tools/cd/sbom.sh ghcr.io/${{ github.repository }}:sha-${{ github.sha }} || true
      - name: Cosign (optional)
        run: tools/cd/sign.sh ghcr.io/${{ github.repository }}:sha-${{ github.sha }} || true
