name: dependency-audit
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - name: PNPM Audit (non-fatal)
        run: pnpm audit --prod --audit-level=high || true
      - name: Save report
        run: pnpm audit --json || true
