name: Docker Build & Push (multi-arch)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Discover Docker contexts
        id: set-matrix
        run: |
          node -e "const {glob}=require('glob');const {dirname,relative}=require('path');glob('**/Dockerfile',{ignore:['**/node_modules/**','.pnpm/**']},(e,files)=>{const uniq=[...new Set(files.map(f=>dirname(f)))];const m={include:uniq.map(p=>({path:p}))};console.log('::set-output name=matrix::'+JSON.stringify(m));});"
  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive image name
        id: meta
        run: |
          NAME=$(echo "${{ matrix.path }}" | tr '/' '-' )
          echo "name=$NAME" >> $GITHUB_OUTPUT
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.path }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate SLSA provenance (generic)
        uses: slsa-framework/slsa-github-generator/actions/generic/create-provenance@v1.10.0
        with:
          subject-path: |
            /github/workspace
        permissions: write-all