
name: Docker Images
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push content-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/content-service
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ghcr.io/${{ github.repository_owner }}/content-service:latest
      - name: Build & Push vitrin-site
        uses: docker/build-push-action@v5
        with:
          context: ./app/vitrin-site
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ghcr.io/${{ github.repository_owner }}/vitrin-site:latest
