name: Docs Verify
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Local link check
        run: node tools/docs-verify.js
