name: Secret Scan — Gitleaks (User)
on:
  pull_request:
    paths:
      - 'app/user-app/**'
      - '.github/workflows/gitleaks-user.yml'
  push:
    branches: [ main ]
    paths:
      - 'app/user-app/**'
      - '.github/workflows/gitleaks-user.yml'
  workflow_dispatch: {}

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --redact -v
