name: OpenAPI Validate

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install (root dev deps)
        run: pnpm install --frozen-lockfile
      - name: Validate OpenAPI
        run: node scripts/validate-openapi.mjs