name: OpenAPI Export
on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    ## SECRETS_ENV: map required secrets here (example)
    # env:
    #   DATABASE_URL: ${{ secrets.BACKEND_DATABASE_URL }}
    steps:
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
              cache: 'pnpm'
          - uses: pnpm/action-setup@v4
            with:
              version: 9
          - run: pnpm install --frozen-lockfile
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Start infra
        run: docker compose --profile infra up -d db redis rabbitmq minio
      - name: Build services
        run: docker compose --profile dev build
      - name: Run services
        run: docker compose --profile dev up -d
      - name: Export OpenAPI
        run: |
          mkdir -p openapi
          for s in $(ls services); do
            curl -s http://localhost:4100/docs-json -o openapi/$s.json || true
          done
      - name: Upload OpenAPI
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi
      - name: Shutdown
        if: always()
      - uses: pnpm/action-setup@v4
        with:
          version: 9
        run: docker compose down -v