name: Perf (k6)
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for tests'
        required: true
        default: 'http://localhost:4000'
jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 smoke
        uses: grafana/k6-action@v0.3.1
        with:
          filename: perf/k6/smoke.js
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}
      - name: Upload k6 summary
        uses: actions/upload-artifact@v4
        with:
          name: k6-smoke-summary
          path: perf/k6/smoke-summary.json
