name: Release Please
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: ${{ github.event.repository.name }}
          bump-minor-pre-major: true
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"refactor","section":"Refactoring","hidden":false},
              {"type":"docs","section":"Docs","hidden":false},
              {"type":"build","section":"Build System","hidden":true},
              {"type":"ci","section":"CI/CD","hidden":true},
              {"type":"chore","section":"Chores","hidden":true},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
