name: Release Dry-Run

on:
  workflow_dispatch:

jobs:
  publish-dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: pnpm pack (all)
        run: pnpm -r pack --pack-destination ./packed
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: packed
          path: packed