name: SCA Audit
on:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: corepack enable && corepack prepare pnpm@9.0.0 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit --json || true
