name: Secret Scan (gitleaks)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: "${GITHUB_TOKEN}"  # from env/secret manager
          GITLEAKS_CONFIG: .gitleaks.toml
