name: Security Scans
on: { push: {}, pull_request: {} }
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with: { args: 'detect --no-git -v -c .gitleaks.toml' }
  sql_injection_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node 20
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Scan SQL injection risks
        run: node tools/scan-injection.js .
