name: Security Scans
on:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks.sarif
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks
          path: gitleaks.sarif
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'CRITICAL,HIGH'
      - uses: actions/upload-artifact@v4
        with:
          name: trivy
          path: trivy.sarif
