name: Trivy Scan

on:
  workflow_run:
    workflows: [ "Docker Build & Push" ]
    types: [ completed ]

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          version: latest

      - name: Scan backend image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/arman-backend:latest || true
          trivy image --severity CRITICAL,HIGH --exit-code 1 ghcr.io/${{ github.repository_owner }}/arman-backend:latest || true

      - name: Scan vitrin image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/arman-vitrin:latest || true
          trivy image --severity CRITICAL,HIGH --exit-code 1 ghcr.io/${{ github.repository_owner }}/arman-vitrin:latest || true
