apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "armanfit-admin.fullname" . }}-deny-all
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "armanfit-admin.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
