{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwtSecretName }}
type: Opaque
stringData:
  {{ .Values.secrets.jwtSecretKey }}: {{ .Values.env.JWT_SECRET | default "CHANGE_ME" | quote }}
  {{ .Values.secrets.databaseUrlKey }}: {{ .Values.env.DATABASE_URL | default "postgresql://postgres:postgres@postgres:5432/armanfit_backend?schema=public" | quote }}
{{- end }}
