apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: armanfit
data:
  MINIO_ENDPOINT: "REDACTED"  # redacted
  MINIO_PORT: "REDACTED"  # redacted
  S3_BUCKET: "REDACTED"  # redacted
