apiVersion: apps/v1
kind: Deployment
metadata:
  name: armanfit-backend
  labels:
    app: armanfit-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: armanfit-backend
  template:
    metadata:
      labels:
        app: armanfit-backend
    spec:
      containers:
      - name: backend
          envFrom:
            - secretRef:
                name: armanfit-backend-env
        image: your-registry/armanfit-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '4000'
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: armanfit-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: armanfit-secrets
              key: JWT_SECRET
        `00
          initialDelaySeconds: 10
          periodSeconds: 10
        `00
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: armanfit-backend
spec:
  selector:
    app: armanfit-backend
  ports:
  - name: http
    port: 80
    targetPort: 4000
