apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: arman
spec:
  replicas: 1
  selector:
    matchLabels: { app: site }
  template:
    metadata:
      labels: { app: site }
    spec:
      containers:
        - name: site
          image: ghcr.io/your/repo/site:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet: { path: "/", port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: arman
spec:
  selector: { app: site }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
