apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "armanfit.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "armanfit.name" . }}
