receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlphttp:
    endpoint: http://tempo:4318
  logging:
    loglevel: warn

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]