server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
ingester:
  trace_idle_period: 10s
  max_block_bytes: 1000000
compactor:
  compaction:
    block_retention: 48h
metrics_generator:
  registry:
    external_labels:
      source: tempo
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks