apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      \1        resources:
          {{- toYaml .Values.resources | nindent 10 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: {{ .Values.service.port }}