apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mobile.armanfit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mobile
                port:
                  number: 19000