apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
  labels: { app: backend-canary }
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend-canary }
  template:
    metadata:
      labels: { app: backend-canary }
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports: [{ containerPort: 3000 }]
        env:
        - name: DATABASE_URL
          value: "{{ .Values.env.DATABASE_URL }}"
        readinessProbe:
          httpGet: { path: /readyz, port: 3000 }
        livenessProbe:
          httpGet: { path: /healthz, port: 3000 }
---
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
spec:
  type: ClusterIP
  selector: { app: backend-canary }
  ports:
    - name: http
      port: 80
      targetPort: 3000
