apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/org/armanvarzesh/backend:v93
          command: ["sh","-lc"]
          args:
            - |
              pnpm dlx prisma generate && pnpm dlx prisma migrate deploy
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
