apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: armanfit-backend-external-secret
  namespace: armanfit
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: armanfit-secret-store
    kind: ClusterSecretStore
  target:
    name: armanfit-backend-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef: { key: /armanfit/backend/DATABASE_URL }
    - secretKey: JWT_ACCESS_SECRET
      remoteRef: { key: /armanfit/backend/JWT_ACCESS_SECRET }
    - secretKey: JWT_REFRESH_SECRET
      remoteRef: { key: /armanfit/backend/JWT_REFRESH_SECRET }
    - secretKey: JWT_ISSUER
      remoteRef: { key: /armanfit/backend/JWT_ISSUER }
    - secretKey: JWT_AUDIENCE
      remoteRef: { key: /armanfit/backend/JWT_AUDIENCE }
    - secretKey: REDIS_URL
      remoteRef: { key: /armanfit/backend/REDIS_URL }
