name: Trivy FS Scan
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          scanners: vuln,secret,misconfig,license
          path: .
