
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "REDACTED"  # redacted
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "REDACTED"  # redacted
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-config
data:
  NODE_ENV: "REDACTED"  # redacted
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-panel-config
data:
  NODE_ENV: "REDACTED"  # redacted
