image:
  repository: ghcr.io/armanvarzesh/backend
  tag: v2025.08.18
  pullPolicy: IfNotPresent
  registry: ghcr.io
replicaCount: 2
service:
  type: ClusterIP
  port: 80
  targetPort: 4000
env:
  NODE_ENV: production
  PORT: '4000'
secrets:
  databaseUrlSecret: armanfit-secrets
  databaseUrlKey: DATABASE_URL
  jwtSecretKey: JWT_SECRET
  jwtSecretName: armanfit-secrets
ingress:
  enabled: true
  className: nginx
  host: api.armanvarzesh.com
  tlsSecret: armanfit-backend-tls
  hosts:
  - host: api.armanvarzesh.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: armanfit-tls
    hosts:
    - api.armanvarzesh.com
resources:
  limits:
    cpu: 700m
    memory: 768Mi
  requests:
    cpu: 300m
    memory: 384Mi
externalSecrets:
  enabled: true
  refreshInterval: 1h
  backendType: secretsManager
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: armanfit/backend
      property: DATABASE_URL
  - secretKey: JWT_SECRET
    remoteRef:
      key: armanfit/backend
      property: JWT_SECRET
  targetSecretName: armanfit-secrets
envFromSecretName: armanfit-backend-env
