image:
  registry: ghcr.io
  repository: armanfit/admin
  tag: v2025.08.18
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
ingress:
  enabled: true
  className: nginx
  hosts:
  - host: api.armanvarzesh.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: armanfit-tls
    hosts:
    - api.armanvarzesh.com
env:
  NODE_ENV: production
envFromSecretName: armanfit-backend-env
externalSecrets:
  enabled: false
  secretStoreRef:
    name: global-secrets-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  targetSecretName: armanfit-backend-env
  data: []
