image:
  repository: ghcr.io/org/armanvarzesh/backend
  tag: latest
service:
  type: ClusterIP
  port: 80
env:
  DATABASE_URL: "${PROD_DATABASE_URL}"
ingress:
  enabled: true
  host: "api.example.com"
