name: gitleaks
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""
          args: "--no-banner --redact --verbose"
