name: grype
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Anchore Grype vulnerability scan (FS)
        uses: anchore/scan-action@v3
        with:
          path: .
          fail-build: true
          severity-cutoff: high
