
name: Mobile Detox
on:
  workflow_dispatch:
  pull_request:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: { node-version: 20 }
    - run: npm i -g detox-cli
    - run: pnpm install --frozen-lockfile=false
    - name: Build Android (placeholder)
      run: echo "./gradlew assembleDebug"
    - name: Detox Test (placeholder)
      run: echo "detox test -c android.debug"
  ios:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '15.4' }
    - uses: actions/setup-node@v4
      with: { node-version: 20 }
    - run: npm i -g detox-cli
    - run: pnpm install --frozen-lockfile=false
    - name: Build iOS (placeholder)
      run: echo "xcodebuild build -scheme App"
    - name: Detox Test (placeholder)
      run: echo "detox test -c ios.debug"
