
name: Phase1 CI
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.6.0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm -w run build || true
      - run: pnpm -w run test || true
      - run: pnpm -w run coverage:check || true
