
name: PR Preview (Build & Deploy)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push gateway image
      uses: docker/build-push-action@v6
      with:
        context: ./services/api-gateway
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/av90-gateway:${{ github.sha }}
    - name: Upload image tag
      run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

  deploy-preview:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with: { version: 'v1.29.4' }
    - name: Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
    - name: Helm install/upgrade
      uses: azure/setup-helm@v4
    - name: Deploy
      run: |
        ns=av-prev-${{ github.run_id }}
        kubectl create ns $ns || true
        helm upgrade --install av-gw-$ns deploy/helm --namespace $ns --set image.tag=${{ env.IMAGE_TAG }}
