
name: PR Preview (Bake all)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  buildx-bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Bake & push
      uses: docker/bake-action@v5
      env:
        REGISTRY: ghcr.io
        OWNER: ${{ github.repository_owner }}
        TAG: ${{ github.sha }}
      with:
        files: docker-bake.hcl
        push: true
        provenance: false

  deploy:
    needs: buildx-bake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v4
      with: { version: 'v1.29.4' }
    - uses: azure/setup-helm@v4
    - name: Kubeconfig
      run: echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
    - name: Render values
      run: |
        cat > deploy/helm/values/preview-tag.yaml <<YAML
        images:
          gateway: ghcr.io/${{ github.repository_owner }}/av90-gateway:${{ github.sha }}
          nutrition: ghcr.io/${{ github.repository_owner }}/av90-nutrition:${{ github.sha }}
          activities: ghcr.io/${{ github.repository_owner }}/av90-activities:${{ github.sha }}
          challenges: ghcr.io/${{ github.repository_owner }}/av90-challenges:${{ github.sha }}
          courses: ghcr.io/${{ github.repository_owner }}/av90-courses:${{ github.sha }}
          kpis: ghcr.io/${{ github.repository_owner }}/av90-kpis:${{ github.sha }}
          affiliate: ghcr.io/${{ github.repository_owner }}/av90-affiliate:${{ github.sha }}
          inbox: ghcr.io/${{ github.repository_owner }}/av90-inbox:${{ github.sha }}
          assessments: ghcr.io/${{ github.repository_owner }}/av90-assessments:${{ github.sha }}
          rewards: ghcr.io/${{ github.repository_owner }}/av90-rewards:${{ github.sha }}
          medical: ghcr.io/${{ github.repository_owner }}/av90-medical:${{ github.sha }}
        YAML
    - name: Deploy Helm preview
      run: |
        ns=av-prev-${{ github.run_id }}
        kubectl create ns $ns || true
        helm upgrade --install av90-$ns deploy/helm --namespace $ns -f deploy/helm/values/preview-tag.yaml
