name: Release Images
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install

      - name: Build & push gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/gateway:${{ github.ref_name }}
          build-args: |
            WORKSPACE=@arman/gateway

      - name: Build & push bff
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/bff:${{ github.ref_name }}

      - name: Build & push payments
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/payments:${{ github.ref_name }}

      - name: Build & push notifications
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/notifications:${{ github.ref_name }}

      - name: Build & push coach
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/coach:${{ github.ref_name }}

      - name: Build & push chat
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/chat:${{ github.ref_name }}

      - name: Build & push activities
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.workspaces
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/activities:${{ github.ref_name }}
