name: zap-baseline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.ZAP_TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
