{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arman-live.fullname" . }}-backend
  labels: {{- toYaml .Values.prometheus.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "arman-live.fullname" . }}-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
